version: '3'
services:
  app:
    container_name: express-mongo
    restart: always
    build: ./app
    ports:
      - "127.0.0.1:4000:4001"
    volumes:
      - ./app:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"